### ISSUE TITLE
Proper credits

### ISSUE THREAD

**Issue by Mystifi** [TellTales/Spark#8]
Hei hei! Sorry to bother, but can you please attribute code borrowed from SpacialGaze developers (mainly within the chat plugins) to us, please? Some of the files already have them in header comments, but it's just a courtesy thing; I always try and credit others for their code.

**Comment by Mystifi** [comment]
It could be as easy as just stating in the README "All code belongs to their rightful owners," or "Various chat-plugins borrowed from SpacialGaze," with a hyperlink to our GitHub.

**Comment by zellman01** [comment]
Would you be fine with a command or something in that nature?

**Comment by Mystifi** [comment]
A command sounds nice, as long as it incorporates all of the necessary credits.

**Comment by Mystifi** [comment]
If you would like, I can send a PR about it.

**Comment by zellman01** [comment]
I don't know what plugins was exactly used, so I just generalized it to give some credits to SpecialGaze

**Comment by Mystifi** [comment]
Merci beaucoup.
